/*
 * Copyright 2026 Harry Timothy Tumalewa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.harrytmthy.stitch.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.google.devtools.ksp.symbol.KSFile
import com.harrytmthy.stitch.annotations.BindingRequester
import com.harrytmthy.stitch.annotations.ContributedBinding
import com.harrytmthy.stitch.annotations.RegisteredScope
import com.harrytmthy.stitch.annotations.RequestedField
import com.harrytmthy.stitch.compiler.StitchSymbolProcessor.Companion.GENERATED_PACKAGE_NAME
import com.harrytmthy.stitch.compiler.consts.BindingKind
import com.harrytmthy.stitch.compiler.model.BindingDeclaration
import com.harrytmthy.stitch.compiler.model.LocalScanResult
import com.harrytmthy.stitch.compiler.model.ProvidedBinding
import com.harrytmthy.stitch.compiler.model.RequestedBinding
import com.harrytmthy.stitch.compiler.model.Scope
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.asClassName
import java.io.OutputStreamWriter

class ContributionCodeGenerator(private val codeGenerator: CodeGenerator) {

    fun generate(moduleKey: String, localScanResult: LocalScanResult) {
        if (localScanResult.customScopeByCanonicalName.isNotEmpty()) {
            val sortedCustomScopes = localScanResult.getSortedRegisteredScopesWithId()
            for ((scope, id) in sortedCustomScopes) {
                val dependency = localScanResult.scopeDependencies[scope] as? Scope.Custom
                val dependencyId = sortedCustomScopes.getOrDefault(dependency, 0)
                val source = localScanResult.scopeSources.getValue(scope)
                generateScopeContribution(id, scope, dependencyId, source, moduleKey)
            }
        }
        val sortedBindings = localScanResult.getSortedBindingsWithId()
        for ((binding, id) in sortedBindings) {
            val dependencyIds = (binding as? ProvidedBinding)?.dependencies
                ?.map(sortedBindings::getValue)
                .orEmpty()
            val source = localScanResult.providedBindingSources.getValue(binding)
            generateBindingContribution(id, binding, dependencyIds, source, moduleKey)
        }
        val sortedRequestedBindings = localScanResult.getSortedRequestedBindings()
        var id = 1
        for ((requester, fields) in sortedRequestedBindings) {
            val bindingIds = fields.map(sortedBindings::getValue)
            val source = localScanResult.requesterSources.getValue(requester)
            generateRequesterContribution(id++, requester, fields, bindingIds, source, moduleKey)
        }
    }

    private fun generateScopeContribution(
        id: Int,
        scope: Scope.Custom,
        dependencyId: Int,
        source: KSFile,
        moduleKey: String,
    ) {
        val annotation = AnnotationSpec.builder(RegisteredScope::class).apply {
            addMember("id = %L", id)
            addMember("originalName = %S", scope.originalName)
            addMember("canonicalName = %S", scope.canonicalName)
            addMember("qualifiedName = %S", scope.qualifiedName)
            addMember("location = %S", scope.location)
            addMember("dependsOn = %L", dependencyId)
        }.build()
        val fileName = "GeneratedScope${id}_$moduleKey"
        val outputObject = TypeSpec.objectBuilder(fileName)
            .addAnnotation(annotation)
            .build()
        val file = FileSpec.builder(GENERATED_PACKAGE_NAME, fileName)
            .addFileComment("Generated by Stitch KSP Compiler - DO NOT EDIT")
            .addType(outputObject)
            .build()
        val outputStream = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, sources = arrayOf(source)),
            packageName = GENERATED_PACKAGE_NAME,
            fileName = fileName,
        )
        OutputStreamWriter(outputStream).use(file::writeTo)
    }

    private fun generateBindingContribution(
        id: Int,
        binding: BindingDeclaration,
        dependencyIds: List<Int>,
        source: KSFile,
        moduleKey: String,
    ) {
        val contributeAnnotation = AnnotationSpec.builder(ContributedBinding::class).apply {
            addMember("id = %L", id)
            addMember("type = %S", binding.type)
            addMember("qualifier = %S", binding.qualifier?.encode().orEmpty())
            if (binding is ProvidedBinding) {
                addMember("scope = %S", binding.scope?.canonicalName.orEmpty())
                addMember("nullable = %L", binding.nullable)
                addMember("location = %S", binding.location)
                addMember("kind = %L", binding.kind)
                addMember("providerPackageName = %S", binding.providerPackageName)
                addMember("providerFunctionName = %S", binding.providerFunctionName)
                addMember("providerClassName = %S", binding.providerClassName)
                addMember("dependsOn = [%L]", dependencyIds.joinToString(", "))
            } else {
                addMember("scope = \"\"")
                addMember("nullable = %L", false)
                addMember("location = %S", binding.location)
                addMember("kind = %L", BindingKind.REQUESTED)
                addMember("providerPackageName = \"\"")
                addMember("providerFunctionName = \"\"")
                addMember("providerClassName = \"\"")
                addMember("dependsOn = []")
            }
        }.build()
        val fileName = "GeneratedBinding${id}_$moduleKey"
        val outputObject = TypeSpec.objectBuilder(fileName)
            .addAnnotation(contributeAnnotation)
            .build()
        val file = FileSpec.builder(GENERATED_PACKAGE_NAME, fileName)
            .addFileComment("Generated by Stitch KSP Compiler - DO NOT EDIT")
            .addType(outputObject)
            .build()
        val outputStream = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, sources = arrayOf(source)),
            packageName = GENERATED_PACKAGE_NAME,
            fileName = fileName,
        )
        OutputStreamWriter(outputStream).use(file::writeTo)
    }

    private fun generateRequesterContribution(
        id: Int,
        requester: String,
        fields: List<RequestedBinding>,
        bindingIds: List<Int>,
        source: KSFile,
        moduleKey: String,
    ) {
        val contributeAnnotation = AnnotationSpec.builder(BindingRequester::class).apply {
            addMember("name = %S", requester)
            addMember("fields = %L", buildRequestedFields(fields, bindingIds))
        }.build()
        val fileName = "GeneratedBindingRequester${id}_$moduleKey"
        val outputObject = TypeSpec.objectBuilder(fileName)
            .addAnnotation(contributeAnnotation)
            .build()
        val file = FileSpec.builder(GENERATED_PACKAGE_NAME, fileName)
            .addFileComment("Generated by Stitch KSP Compiler - DO NOT EDIT")
            .addType(outputObject)
            .build()
        val outputStream = codeGenerator.createNewFile(
            dependencies = Dependencies(aggregating = false, sources = arrayOf(source)),
            packageName = GENERATED_PACKAGE_NAME,
            fileName = fileName,
        )
        OutputStreamWriter(outputStream).use(file::writeTo)
    }

    private fun buildRequestedFields(
        fields: List<RequestedBinding>,
        bindingIds: List<Int>,
    ): CodeBlock {
        val requestedFieldClass = RequestedField::class.asClassName()
        return CodeBlock.builder().apply {
            add("[\n")
            indent()
            fields.forEachIndexed { index, requested ->
                val id = bindingIds[index]
                add("%T(\n", requestedFieldClass)
                indent()
                add("bindingId = %L,\n", id)
                add("fieldName = %S,\n", requested.fieldName)
                unindent()
                add("),\n")
            }
            unindent()
            add("]")
        }.build()
    }

    /**
     * Returns sorted bindings by stable IDs, which includes:
     * - provided bindings + their dependencies
     * - requested bindings
     *
     * Bindings that are already provided will be prioritized.
     */
    private fun LocalScanResult.getSortedBindingsWithId(): Map<BindingDeclaration, Int> {
        val bindings = LinkedHashSet<BindingDeclaration>()
        bindings += providedBindings.values
        for (providedBinding in providedBindings.values) {
            providedBinding.dependencies?.forEach { dependency ->
                if (dependency !in providedBindings) {
                    bindings.add(dependency)
                }
            }
        }
        for (requestedBindings in requestedBindings.values) {
            for (requestedBinding in requestedBindings) {
                if (requestedBinding !in providedBindings) {
                    bindings.add(requestedBinding)
                }
            }
        }
        var nextId = 1
        return bindings.sortedWith(compareBy({ it.type }, { it.qualifier?.toString().orEmpty() }))
            .associateWith { nextId++ }
    }

    /**
     * Produces stable ordering for Gradle cache hits.
     */
    private fun LocalScanResult.getSortedRequestedBindings(): Map<String, List<RequestedBinding>> =
        requestedBindings.toSortedMap() // sort by requester's FQN
            .mapValues { (_, fields) ->
                val comparator = compareBy<RequestedBinding>(
                    { it.fieldName },
                    { it.type },
                    { it.qualifier?.toString().orEmpty() },
                )
                fields.sortedWith(comparator)
            }

    /**
     * Returns sorted bindings by stable IDs.
     */
    private fun LocalScanResult.getSortedRegisteredScopesWithId(): Map<Scope.Custom, Int> {
        var nextId = 1
        return customScopeByCanonicalName.values.sortedWith(compareBy { it.canonicalName })
            .associateWith { nextId++ }
    }
}
