/*
 * Copyright 2026 Harry Timothy Tumalewa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.harrytmthy.stitch.compiler

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.harrytmthy.stitch.compiler.StitchSymbolProcessor.Companion.GENERATED_PACKAGE_NAME
import com.harrytmthy.stitch.compiler.consts.BindingKind
import com.harrytmthy.stitch.compiler.model.Qualifier
import com.harrytmthy.stitch.compiler.model.Scope
import com.harrytmthy.stitch.compiler.model.ValidatedBinding
import com.harrytmthy.stitch.compiler.model.plan.InjectorPlan
import com.harrytmthy.stitch.compiler.model.plan.RequestedFieldPlan
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.TypeSpec
import java.io.OutputStreamWriter

object ScopedGraphGenerator {

    fun generate(codeGenerator: CodeGenerator, injectorPlans: List<InjectorPlan>) {
        for (injectorPlan in injectorPlans) {
            val fileName = graphClassName(injectorPlan.scope)
            val outputType = if (injectorPlan.scope is Scope.Singleton) {
                buildSingletonGraphType(injectorPlan)
            } else {
                buildGraphType(injectorPlan)
            }
            val file = FileSpec.builder(GENERATED_PACKAGE_NAME, fileName)
                .addFileComment("Generated by Stitch KSP Compiler - DO NOT EDIT")
                .addType(outputType)
                .build()
            val outputStream = codeGenerator.createNewFile(
                dependencies = Dependencies.ALL_FILES,
                packageName = GENERATED_PACKAGE_NAME,
                fileName = fileName,
            )
            OutputStreamWriter(outputStream).use(file::writeTo)
        }
    }

    private fun buildSingletonGraphType(plan: InjectorPlan): TypeSpec {
        val injectorClass = ClassName("com.harrytmthy.stitch.api", "Injector")
        return TypeSpec.objectBuilder(graphClassName(plan.scope))
            .addAnnotation(
                AnnotationSpec.builder(Suppress::class)
                    .addMember("%S", "UNCHECKED_CAST")
                    .build(),
            )
            .addSuperinterface(injectorClass)
            .addProperty(
                PropertySpec.builder("id", Int::class, KModifier.OVERRIDE)
                    .initializer("0")
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("currentScope", String::class, KModifier.OVERRIDE)
                    .initializer("%S", "singleton")
                    .build(),
            )
            .addProperty(
                PropertySpec.builder(
                    "upstream",
                    injectorClass.copy(nullable = true),
                    KModifier.OVERRIDE,
                ).initializer("null").build(),
            )
            .apply {
                addProviderClassFields(plan)
                addDclHolderFields(plan)
                addBindingAccessors(plan)
                addTypedInjectFunctions(plan)
                addAnyInjectOverride(plan)
                addCreateChildFunction(plan)
            }
            .build()
    }

    private fun buildGraphType(plan: InjectorPlan): TypeSpec {
        val injectorClass = ClassName("com.harrytmthy.stitch.api", "Injector")
        val parentGraphClass = plan.parentScope?.let { ClassName(GENERATED_PACKAGE_NAME, graphClassName(it)) }

        val constructor = FunSpec.constructorBuilder()
            .addParameter("id", Int::class)
            .addParameter("currentScope", String::class)
            .apply {
                if (parentGraphClass != null) {
                    addParameter("upstream", parentGraphClass)
                }
            }
            .build()

        return TypeSpec.classBuilder(graphClassName(plan.scope))
            .addAnnotation(
                AnnotationSpec.builder(Suppress::class)
                    .addMember("%S", "UNCHECKED_CAST")
                    .build(),
            )
            .primaryConstructor(constructor)
            .addSuperinterface(injectorClass)
            .addProperty(
                PropertySpec.builder("id", Int::class, KModifier.OVERRIDE)
                    .initializer("id")
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("currentScope", String::class, KModifier.OVERRIDE)
                    .initializer("currentScope")
                    .build(),
            )
            .addProperty(
                PropertySpec.builder(
                    "upstream",
                    parentGraphClass!!,
                    KModifier.OVERRIDE,
                ).initializer("upstream").build(),
            )
            .apply {
                addProviderClassFields(plan)
                addDclHolderFields(plan)
                addBindingAccessors(plan)
                addTypedInjectFunctions(plan)
                addAnyInjectOverride(plan)
                addCreateChildFunction(plan)
            }
            .build()
    }

    private fun TypeSpec.Builder.addProviderClassFields(plan: InjectorPlan) {
        val seen = HashSet<String>()
        for (binding in plan.ownedBindings) {
            if (binding.kind != BindingKind.PROVIDED_IN_CLASS) {
                continue
            }
            val fqcn = "${binding.providerPackageName}.${binding.providerClassName}"
            if (!seen.add(fqcn)) {
                continue
            }
            addProperty(
                PropertySpec.builder(
                    providerFieldName(binding),
                    ClassName.bestGuess(fqcn),
                    KModifier.PRIVATE,
                ).initializer("%T()", ClassName.bestGuess(fqcn))
                    .build(),
            )
        }
    }

    private fun TypeSpec.Builder.addDclHolderFields(plan: InjectorPlan) {
        val dclHolderClass = ClassName("com.harrytmthy.stitch.api", "DclHolder")
        for (binding in plan.ownedBindings) {
            if (!binding.requiresDclHolder()) {
                continue
            }
            val holderType = dclHolderClass.parameterizedBy(ClassName.bestGuess(binding.type))
            addProperty(
                PropertySpec.builder(
                    accessorName(binding),
                    holderType,
                    KModifier.PRIVATE,
                ).initializer("%T()", holderType)
                    .build(),
            )
        }
    }

    private fun TypeSpec.Builder.addBindingAccessors(plan: InjectorPlan) {
        for (binding in plan.ownedBindings) {
            addFunction(buildBindingAccessor(plan, binding))
        }
    }

    private fun buildBindingAccessor(plan: InjectorPlan, binding: ValidatedBinding): FunSpec {
        return FunSpec.builder(accessorName(binding))
            .returns(ClassName.bestGuess(binding.type))
            .addCode(buildBindingAccessorBody(plan, binding))
            .build()
    }

    private fun buildBindingAccessorBody(
        plan: InjectorPlan,
        binding: ValidatedBinding,
    ): CodeBlock {
        if (binding.kind == BindingKind.PROVIDED_ALIAS) {
            val dependency = binding.dependencies!!.single()
            return CodeBlock.builder()
                .addStatement("return %L", dependencyAccess(plan.scope, dependency))
                .build()
        }

        if (binding.declaredScope == null) {
            return CodeBlock.builder()
                .addStatement("return %L", createBindingExpression(plan.scope, binding))
                .build()
        }

        val holderName = accessorName(binding)
        val dclHolderClass = ClassName("com.harrytmthy.stitch.api", "DclHolder")

        return CodeBlock.builder().apply {
            addStatement("val cached = %N.reference", holderName)
            beginControlFlow("if (cached !== %T.Uninitialized)", dclHolderClass)
            addStatement("return cached as %T", ClassName.bestGuess(binding.type))
            endControlFlow()

            beginControlFlow("synchronized(%N.lock)", holderName)
            addStatement("val locked = %N.reference", holderName)
            beginControlFlow("if (locked !== %T.Uninitialized)", dclHolderClass)
            addStatement("return locked as %T", ClassName.bestGuess(binding.type))
            endControlFlow()

            addStatement("val created = %L", createBindingExpression(plan.scope, binding))
            addStatement("%N.reference = created", holderName)
            addStatement("return created")
            endControlFlow()
        }.build()
    }

    private fun createBindingExpression(
        currentScope: Scope,
        binding: ValidatedBinding,
    ): CodeBlock {
        val dependencyArgs = binding.dependencies
            ?.map { dependencyAccess(currentScope, it) }
            .orEmpty()

        return when (binding.kind) {
            BindingKind.PROVIDED_IN_CONSTRUCTOR -> {
                CodeBlock.builder().apply {
                    add("%T(", ClassName.bestGuess(binding.type))
                    dependencyArgs.forEachIndexed { index, arg ->
                        if (index > 0) add(", ")
                        add("%L", arg)
                    }
                    add(")")
                }.build()
            }

            BindingKind.PROVIDED_IN_TOP_LEVEL -> {
                CodeBlock.builder().apply {
                    add("%M(", MemberName(binding.providerPackageName, binding.providerFunctionName))
                    dependencyArgs.forEachIndexed { index, arg ->
                        if (index > 0) add(", ")
                        add("%L", arg)
                    }
                    add(")")
                }.build()
            }

            BindingKind.PROVIDED_IN_OBJECT -> {
                CodeBlock.builder().apply {
                    add(
                        "%T.%N(",
                        ClassName.bestGuess("${binding.providerPackageName}.${binding.providerClassName}"),
                        binding.providerFunctionName,
                    )
                    dependencyArgs.forEachIndexed { index, arg ->
                        if (index > 0) add(", ")
                        add("%L", arg)
                    }
                    add(")")
                }.build()
            }

            BindingKind.PROVIDED_IN_CLASS -> {
                CodeBlock.builder().apply {
                    add("%N.%N(", providerFieldName(binding), binding.providerFunctionName)
                    dependencyArgs.forEachIndexed { index, arg ->
                        if (index > 0) add(", ")
                        add("%L", arg)
                    }
                    add(")")
                }.build()
            }

            else -> error("Unsupported binding kind: ${binding.kind}")
        }
    }

    private fun dependencyAccess(
        currentScope: Scope,
        dependency: ValidatedBinding,
    ): CodeBlock {
        if (dependency.owningScope == currentScope) {
            return CodeBlock.of("%N()", accessorName(dependency))
        }

        val chainCount = currentScope.depth - dependency.owningScope.depth
        val prefix = buildString {
            repeat(chainCount) {
                append("upstream.")
            }
        }
        return CodeBlock.of("%L%N()", prefix, accessorName(dependency))
    }

    private fun TypeSpec.Builder.addTypedInjectFunctions(plan: InjectorPlan) {
        for ((requesterFqn, fields) in plan.requestedBindings) {
            addFunction(
                FunSpec.builder("inject")
                    .addParameter("target", ClassName.bestGuess(requesterFqn))
                    .addCode(buildTypedInjectBody(plan.scope, fields))
                    .build(),
            )
        }
    }

    private fun buildTypedInjectBody(
        currentScope: Scope,
        fields: List<RequestedFieldPlan>,
    ): CodeBlock =
        CodeBlock.builder().apply {
            for (field in fields) {
                addStatement(
                    "target.%N = %L",
                    field.fieldName,
                    dependencyAccess(currentScope, field.binding),
                )
            }
        }.build()

    private fun TypeSpec.Builder.addAnyInjectOverride(plan: InjectorPlan) {
        addFunction(
            FunSpec.builder("inject")
                .addModifiers(KModifier.OVERRIDE)
                .addParameter("target", Any::class)
                .addCode(
                    CodeBlock.builder().apply {
                        if (plan.requestedBindings.isEmpty()) {
                            addStatement("return")
                        } else {
                            beginControlFlow("when (target)")
                            for (requesterFqn in plan.requestedBindings.keys) {
                                addStatement("is %T -> inject(target)", ClassName.bestGuess(requesterFqn))
                            }
                            addStatement("else -> Unit")
                            endControlFlow()
                        }
                    }.build(),
                )
                .build(),
        )
    }

    private fun TypeSpec.Builder.addCreateChildFunction(plan: InjectorPlan) {
        val injectorClass = ClassName("com.harrytmthy.stitch.api", "Injector")

        addFunction(
            FunSpec.builder("createInjectorForChildScope")
                .addModifiers(KModifier.OVERRIDE)
                .addParameter("scopeName", String::class)
                .returns(injectorClass)
                .addCode(
                    CodeBlock.builder().apply {
                        beginControlFlow("return when (scopeName)")
                        for (childScope in plan.directChildScopes) {
                            addStatement(
                                "%S -> %T(%T.nextId(), scopeName, this)",
                                childScope.canonicalName,
                                ClassName(GENERATED_PACKAGE_NAME, graphClassName(childScope)),
                                injectorClass,
                            )
                        }
                        addStatement(
                            "else -> %T.childNotFoundError(currentScope, scopeName)",
                            injectorClass,
                        )
                        endControlFlow()
                    }.build(),
                )
                .build(),
        )
    }

    private fun graphClassName(scope: Scope): String =
        "Stitch${scope.originalName.replaceFirstChar(Char::uppercase)}Graph"

    private fun accessorName(binding: ValidatedBinding): String =
        buildString {
            append(baseTypeName(binding.type))
            when (val qualifier = binding.qualifier) {
                null -> Unit

                is Qualifier.Named -> {
                    append("_named_")
                    append(sanitizeName(qualifier.value))
                }
            }
        }

    private fun providerFieldName(binding: ValidatedBinding): String =
        binding.providerClassName.replaceFirstChar(Char::lowercase)

    private fun baseTypeName(fqcn: String): String {
        val raw = fqcn.substringAfterLast('.').substringAfterLast('$')
        return sanitizeName(raw).replaceFirstChar(Char::lowercase)
    }

    private fun sanitizeName(raw: String): String =
        raw.replace(Regex("[^A-Za-z0-9_]"), "_")
            .replace(Regex("_+"), "_")
            .trim('_')
            .ifBlank { "value" }

    private fun ValidatedBinding.requiresDclHolder(): Boolean =
        declaredScope != null && kind != BindingKind.PROVIDED_ALIAS
}
