/*
 * Copyright 2025 Harry Timothy Tumalewa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.harrytmthy.stitch.internal

import com.harrytmthy.stitch.api.Qualifier
import com.harrytmthy.stitch.exception.MissingBindingException

/**
 * Interface for compile-time generated dependency lookup tables.
 *
 * Implementations of this interface are generated by the Stitch KSP compiler
 * based on @Module, @Provides, @Inject, and @EntryPoint annotations. This enables
 * O(1) dependency resolution for compile-time registered dependencies.
 *
 * **Note**: This is a public API implemented by generated code. Do not implement directly.
 */
interface DependencyTable {

    /**
     * Looks up and resolves a dependency for the given type and qualifier.
     *
     * Unlike the SL path which caches instances in [Registry], the DI path maintains
     * its own cache within [Provider] instances to prevent unwanted side-effects.
     *
     * @param type The class type of the dependency to look up
     * @param qualifier Optional qualifier to differentiate between multiple bindings
     * @return The resolved dependency instance
     * @throws MissingBindingException if the binding is not found in the DI table
     */
    fun <T : Any> get(type: Class<T>, qualifier: Qualifier?): T

    /**
     * Injects dependencies into @Inject annotated fields of an @EntryPoint instance.
     *
     * This method is used for field injection in classes that cannot use constructor
     * injection (e.g. Android Activities, Fragments). The class must be annotated
     * with @EntryPoint for member injection to be generated.
     *
     * @param instance The object instance to inject dependencies into
     * @param type The class type of the instance (used for lookup in member injector map)
     */
    fun <T : Any> injectMembers(instance: T, type: Class<T>)
}
