/*
 * Copyright 2026 Harry Timothy Tumalewa
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.harrytmthy.stitch.ksp

import com.google.devtools.ksp.processing.CodeGenerator
import com.google.devtools.ksp.processing.Dependencies
import com.harrytmthy.stitch.api.DclHolder
import com.harrytmthy.stitch.api.Injector
import com.harrytmthy.stitch.api.StitchInjector
import com.harrytmthy.stitch.ksp.StitchSymbolProcessor.Companion.GENERATED_PACKAGE_NAME
import com.harrytmthy.stitch.ksp.consts.BindingKind
import com.harrytmthy.stitch.ksp.model.Qualifier
import com.harrytmthy.stitch.ksp.model.Scope
import com.harrytmthy.stitch.ksp.model.ValidatedBinding
import com.harrytmthy.stitch.ksp.model.plan.InjectorPlan
import com.harrytmthy.stitch.ksp.model.plan.RequestedFieldPlan
import com.squareup.kotlinpoet.AnnotationSpec
import com.squareup.kotlinpoet.ClassName
import com.squareup.kotlinpoet.CodeBlock
import com.squareup.kotlinpoet.FileSpec
import com.squareup.kotlinpoet.FunSpec
import com.squareup.kotlinpoet.KModifier
import com.squareup.kotlinpoet.MemberName
import com.squareup.kotlinpoet.ParameterSpec
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.PropertySpec
import com.squareup.kotlinpoet.STAR
import com.squareup.kotlinpoet.TypeSpec
import com.squareup.kotlinpoet.TypeVariableName
import com.squareup.kotlinpoet.asClassName
import java.io.OutputStreamWriter

object ScopedGraphGenerator {

    fun generate(codeGenerator: CodeGenerator, injectorPlans: List<InjectorPlan>) {
        for (injectorPlan in injectorPlans) {
            val fileName = graphClassName(injectorPlan.scope)
            val outputType = if (injectorPlan.scope is Scope.Singleton) {
                buildSingletonGraphType(injectorPlan.scope)
            } else {
                buildGraphType(injectorPlan.scope, injectorPlan.parentScope)
            }.apply {
                addProviderClassFields(injectorPlan)
                addDclHolderFields(injectorPlan)
                addBindingAccessors(injectorPlan)
                addTypedInjectFunctions(injectorPlan)
                addAnyInjectOverride(injectorPlan)
                addCreateChildFunction(injectorPlan)
                addUniversalGetterFunction(injectorPlan)
            }.build()
            val file = FileSpec.builder(GENERATED_PACKAGE_NAME, fileName)
                .addFileComment("Generated by Stitch KSP Compiler - DO NOT EDIT")
                .addType(outputType)
                .build()
            val outputStream = codeGenerator.createNewFile(
                dependencies = Dependencies.ALL_FILES,
                packageName = GENERATED_PACKAGE_NAME,
                fileName = fileName,
            )
            OutputStreamWriter(outputStream).use(file::writeTo)
        }
    }

    private fun buildSingletonGraphType(scope: Scope): TypeSpec.Builder {
        val injectorClass = Injector::class.asClassName()
        return TypeSpec.classBuilder(graphClassName(scope))
            .addAnnotation(
                AnnotationSpec.builder(Suppress::class)
                    .addMember("%S", "UNCHECKED_CAST")
                    .build(),
            )
            .addSuperinterface(injectorClass)
            .addProperty(
                PropertySpec.builder("id", Int::class, KModifier.OVERRIDE)
                    .initializer("0")
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("currentScope", String::class, KModifier.OVERRIDE)
                    .initializer("%S", "singleton")
                    .build(),
            )
            .addProperty(
                PropertySpec.builder(
                    "upstream",
                    injectorClass.copy(nullable = true),
                    KModifier.OVERRIDE,
                ).initializer("null").build(),
            )
    }

    private fun buildGraphType(scope: Scope, parentScope: Scope?): TypeSpec.Builder {
        val injectorClass = Injector::class.asClassName()
        val parentGraphClass = parentScope?.let { ClassName(GENERATED_PACKAGE_NAME, graphClassName(it)) }

        val constructor = FunSpec.constructorBuilder()
            .addParameter("id", Int::class)
            .addParameter("currentScope", String::class)
            .apply {
                if (parentGraphClass != null) {
                    addParameter("upstream", parentGraphClass)
                }
            }
            .build()

        return TypeSpec.classBuilder(graphClassName(scope))
            .addAnnotation(
                AnnotationSpec.builder(Suppress::class)
                    .addMember("%S", "UNCHECKED_CAST")
                    .build(),
            )
            .primaryConstructor(constructor)
            .addSuperinterface(injectorClass)
            .addProperty(
                PropertySpec.builder("id", Int::class, KModifier.OVERRIDE)
                    .initializer("id")
                    .build(),
            )
            .addProperty(
                PropertySpec.builder("currentScope", String::class, KModifier.OVERRIDE)
                    .initializer("currentScope")
                    .build(),
            )
            .addProperty(
                PropertySpec.builder(
                    "upstream",
                    parentGraphClass!!,
                    KModifier.OVERRIDE,
                ).initializer("upstream").build(),
            )
    }

    private fun TypeSpec.Builder.addProviderClassFields(plan: InjectorPlan) {
        val seen = HashSet<String>()
        for (binding in plan.ownedBindings) {
            if (binding.kind != BindingKind.PROVIDED_IN_CLASS) {
                continue
            }
            if (!seen.add(binding.providerClassName)) {
                continue
            }
            addProperty(
                PropertySpec.builder(
                    baseTypeName(binding.providerClassName),
                    ClassName.bestGuess(binding.providerClassName),
                    KModifier.PRIVATE,
                ).initializer("%T()", ClassName.bestGuess(binding.providerClassName))
                    .build(),
            )
        }
    }

    private fun TypeSpec.Builder.addDclHolderFields(plan: InjectorPlan) {
        val dclHolderClass = DclHolder::class.asClassName()
        for (binding in plan.ownedBindings) {
            if (!binding.requiresDclHolder()) {
                continue
            }
            val bindingType = ClassName.bestGuess(binding.type)
                .run {
                    if (binding.nullable) copy(nullable = true) else this
                }
            val holderType = dclHolderClass.parameterizedBy(bindingType)
            addProperty(
                PropertySpec.builder(
                    accessorName(binding),
                    holderType,
                    KModifier.PRIVATE,
                ).initializer("%T()", holderType)
                    .build(),
            )
        }
    }

    private fun TypeSpec.Builder.addBindingAccessors(plan: InjectorPlan) {
        for (binding in plan.ownedBindings) {
            addFunction(buildBindingAccessor(plan, binding))
        }
    }

    private fun buildBindingAccessor(plan: InjectorPlan, binding: ValidatedBinding): FunSpec {
        val returnType = ClassName.bestGuess(binding.type)
            .run {
                if (binding.nullable) copy(nullable = true) else this
            }
        return FunSpec.builder(accessorName(binding))
            .returns(returnType)
            .addCode(buildBindingAccessorBody(plan, binding))
            .build()
    }

    private fun buildBindingAccessorBody(
        plan: InjectorPlan,
        binding: ValidatedBinding,
    ): CodeBlock {
        if (binding.kind == BindingKind.PROVIDED_ALIAS) {
            val dependency = binding.dependencies!!.single()
            return CodeBlock.builder()
                .addStatement("return %L", dependencyAccess(plan.scope, dependency))
                .build()
        }

        if (binding.declaredScope == null) {
            return CodeBlock.builder()
                .addStatement("return %L", createBindingExpression(plan.scope, binding))
                .build()
        }

        val holderName = accessorName(binding)
        val dclHolderClass = DclHolder::class.asClassName()

        return CodeBlock.builder().apply {
            addStatement("val cached = %N.reference", holderName)
            beginControlFlow("if (cached !== %T.Uninitialized)", dclHolderClass)
            addStatement("return cached as %T", ClassName.bestGuess(binding.type))
            endControlFlow()

            beginControlFlow("synchronized(%N.lock)", holderName)
            addStatement("val locked = %N.reference", holderName)
            beginControlFlow("if (locked !== %T.Uninitialized)", dclHolderClass)
            addStatement("return locked as %T", ClassName.bestGuess(binding.type))
            endControlFlow()

            addStatement("val created = %L", createBindingExpression(plan.scope, binding))
            addStatement("%N.reference = created", holderName)
            addStatement("return created")
            endControlFlow()
        }.build()
    }

    private fun createBindingExpression(
        currentScope: Scope,
        binding: ValidatedBinding,
    ): CodeBlock {
        val dependencyArgs = binding.dependencies
            ?.map { dependencyAccess(currentScope, it) }
            .orEmpty()

        return when (binding.kind) {
            BindingKind.PROVIDED_IN_CONSTRUCTOR -> {
                CodeBlock.builder().apply {
                    add("%T(", ClassName.bestGuess(binding.type))
                    dependencyArgs.forEachIndexed { index, arg ->
                        if (index > 0) add(", ")
                        add("%L", arg)
                    }
                    add(")")
                }.build()
            }

            BindingKind.PROVIDED_IN_TOP_LEVEL -> {
                CodeBlock.builder().apply {
                    add("%M(", MemberName(binding.providerPackageName, binding.providerFunctionName))
                    dependencyArgs.forEachIndexed { index, arg ->
                        if (index > 0) add(", ")
                        add("%L", arg)
                    }
                    add(")")
                }.build()
            }

            BindingKind.PROVIDED_IN_OBJECT -> {
                CodeBlock.builder().apply {
                    add(
                        "%T.%N(",
                        ClassName.bestGuess(binding.providerClassName),
                        binding.providerFunctionName,
                    )
                    dependencyArgs.forEachIndexed { index, arg ->
                        if (index > 0) add(", ")
                        add("%L", arg)
                    }
                    add(")")
                }.build()
            }

            BindingKind.PROVIDED_IN_CLASS -> {
                val formattedClassName = baseTypeName(binding.providerClassName)
                CodeBlock.builder().apply {
                    add("%N.%N(", formattedClassName, binding.providerFunctionName)
                    dependencyArgs.forEachIndexed { index, arg ->
                        if (index > 0) add(", ")
                        add("%L", arg)
                    }
                    add(")")
                }.build()
            }

            else -> error("Unsupported binding kind: ${binding.kind}")
        }
    }

    private fun dependencyAccess(
        currentScope: Scope,
        dependency: ValidatedBinding,
    ): CodeBlock {
        if (dependency.owningScope == currentScope) {
            return CodeBlock.of("%N()", accessorName(dependency))
        }

        val chainCount = currentScope.depth - dependency.owningScope.depth
        val prefix = buildString {
            repeat(chainCount) {
                append("upstream.")
            }
        }
        return CodeBlock.of("%L%N()", prefix, accessorName(dependency))
    }

    private fun TypeSpec.Builder.addTypedInjectFunctions(plan: InjectorPlan) {
        for ((requesterFqn, fields) in plan.requestedBindings) {
            addFunction(
                FunSpec.builder("inject")
                    .addParameter("target", ClassName.bestGuess(requesterFqn))
                    .addCode(buildTypedInjectBody(plan.scope, fields))
                    .build(),
            )
        }
    }

    private fun buildTypedInjectBody(
        currentScope: Scope,
        fields: List<RequestedFieldPlan>,
    ): CodeBlock =
        CodeBlock.builder().apply {
            for (field in fields) {
                addStatement(
                    "target.%N = %L",
                    field.fieldName,
                    dependencyAccess(currentScope, field.binding),
                )
            }
        }.build()

    private fun TypeSpec.Builder.addAnyInjectOverride(plan: InjectorPlan) {
        addFunction(
            FunSpec.builder("inject")
                .addModifiers(KModifier.OVERRIDE)
                .addParameter("target", Any::class)
                .addCode(
                    CodeBlock.builder().apply {
                        if (plan.requestedBindings.isEmpty()) {
                            addStatement("return")
                        } else {
                            beginControlFlow("when (target)")
                            for (requesterFqn in plan.requestedBindings.keys) {
                                addStatement("is %T -> inject(target)", ClassName.bestGuess(requesterFqn))
                            }
                            addStatement("else -> Unit")
                            endControlFlow()
                        }
                    }.build(),
                )
                .build(),
        )
    }

    private fun TypeSpec.Builder.addCreateChildFunction(plan: InjectorPlan) {
        val injectorClass = Injector::class.asClassName()

        addFunction(
            FunSpec.builder("createInjectorForChildScope")
                .addModifiers(KModifier.OVERRIDE)
                .addParameter("scopeName", String::class)
                .addParameter("cached", Boolean::class)
                .returns(injectorClass)
                .addCode(
                    CodeBlock.builder().apply {
                        beginControlFlow("return when (scopeName)")
                        for (childScope in plan.directChildScopes) {
                            addStatement(
                                "%S -> %T(%T.nextId(), scopeName, this)",
                                childScope.canonicalName,
                                ClassName(GENERATED_PACKAGE_NAME, graphClassName(childScope)),
                                StitchInjector::class.asClassName(),
                            )
                        }
                        addStatement($$"else -> error(\"Scope '$currentScope' doesn't have a child with name '$scopeName'\")")
                        unindent()
                        add("}.also {\n")
                        indent()
                        beginControlFlow("if (cached)")
                        addStatement("%T.addToCache(it)", StitchInjector::class.asClassName())
                        endControlFlow()
                        unindent()
                        add("}\n")
                        unindent()
                    }.build(),
                )
                .build(),
        )
    }

    private fun TypeSpec.Builder.addUniversalGetterFunction(plan: InjectorPlan) {
        val qualifierClass = com.harrytmthy.stitch.api.Qualifier::class.asClassName()
        val namedClass = com.harrytmthy.stitch.api.Named::class.asClassName()
        val typedClass = com.harrytmthy.stitch.api.Typed::class.asClassName()
        val kClassClass = kotlin.reflect.KClass::class.asClassName()

        addFunction(
            FunSpec.builder("get")
                .addTypeVariable(TypeVariableName("T", Any::class))
                .addModifiers(KModifier.OVERRIDE)
                .addParameter("type", kClassClass.parameterizedBy(STAR))
                .addParameter(
                    ParameterSpec.builder("qualifier", qualifierClass.copy(nullable = true))
                        .build(),
                )
                .returns(TypeVariableName("T"))
                .addCode(buildUniversalGetterBody(plan, namedClass, typedClass))
                .build(),
        )
    }

    private fun buildUniversalGetterBody(
        plan: InjectorPlan,
        namedClass: ClassName,
        typedClass: ClassName,
    ): CodeBlock {
        val bindingsByType = linkedMapOf<String, List<ValidatedBinding>>()
        for (binding in plan.ancestorBindings) {
            bindingsByType.getOrPut(binding.type) { ArrayList() }
        }
        for (binding in plan.ancestorBindings) {
            (bindingsByType.getValue(binding.type) as MutableList<ValidatedBinding>).add(binding)
        }

        return CodeBlock.builder().apply {
            beginControlFlow("return when (type)")

            for ((typeFqn, bindings) in bindingsByType) {
                val typeClass = ClassName.bestGuess(typeFqn)
                add("%T::class -> ", typeClass)

                val unqualified = bindings.firstOrNull { it.qualifier == null }
                val namedBindings = bindings.mapNotNull { binding ->
                    when (val qualifier = binding.qualifier) {
                        is Qualifier.Named -> qualifier.value to binding
                        else -> null
                    }
                }
                val typedBindings = bindings.mapNotNull { binding ->
                    when (val qualifier = binding.qualifier) {
                        is Qualifier.Custom -> qualifier.qualifiedName to binding
                        else -> null
                    }
                }

                when {
                    bindings.size == 1 && unqualified != null -> {
                        addStatement("%L as T", dependencyAccess(plan.scope, unqualified))
                    }

                    else -> {
                        beginControlFlow("")
                        if (unqualified != null) {
                            beginControlFlow("if (qualifier == null)")
                            addStatement("return %L as T", dependencyAccess(plan.scope, unqualified))
                            endControlFlow()
                        }

                        if (namedBindings.isNotEmpty() || typedBindings.isNotEmpty()) {
                            beginControlFlow("when (qualifier)")
                            if (namedBindings.isNotEmpty()) {
                                beginControlFlow("is %T ->", namedClass)
                                beginControlFlow("when (qualifier.value)")
                                for ((name, binding) in namedBindings) {
                                    addStatement(
                                        "%S -> return %L as T",
                                        name,
                                        dependencyAccess(plan.scope, binding),
                                    )
                                }
                                addStatement(
                                    $$"else -> error(\"Binding with type '${type.simpleName}' has no qualifier with name '${qualifier.value}'\")",
                                )
                                endControlFlow()
                                endControlFlow()
                            }

                            if (typedBindings.isNotEmpty()) {
                                beginControlFlow("is %T ->", typedClass)
                                beginControlFlow("when (qualifier.value)")
                                for ((qualifiedName, binding) in typedBindings) {
                                    addStatement(
                                        "%T::class -> return %L as T",
                                        ClassName.bestGuess(qualifiedName),
                                        dependencyAccess(plan.scope, binding),
                                    )
                                }
                                addStatement(
                                    $$"else -> error(\"Binding with type '${type.simpleName}' has no qualifier with type '${qualifier.value.qualifiedName}'\")",
                                )
                                endControlFlow()
                                endControlFlow()
                            }

                            addStatement(
                                $$"else -> error(\"Binding with type '${type.simpleName}' has no matching qualifier '$qualifier'\")",
                            )
                            endControlFlow()
                        } else {
                            addStatement(
                                $$"error(\"Binding with type '${type.simpleName}' has no matching qualifier '$qualifier'\")",
                            )
                        }

                        endControlFlow()
                    }
                }
            }

            addStatement(
                $$"else -> error(\"Binding with type '${type.simpleName}' is not found in $currentScope scope and its ancestors.\")",
            )
            endControlFlow()
        }.build()
    }

    private fun graphClassName(scope: Scope): String =
        "Stitch${scope.originalName.replaceFirstChar(Char::uppercase)}Graph"

    private fun accessorName(binding: ValidatedBinding): String =
        buildString {
            append(baseTypeName(binding.type))
            when (val qualifier = binding.qualifier) {
                null -> Unit

                is Qualifier.Custom -> {
                    append("_custom_")
                    append(sanitizeName(qualifier.qualifiedName))
                }

                is Qualifier.Named -> {
                    append("_named_")
                    append(sanitizeName(qualifier.value))
                }
            }
        }

    private fun baseTypeName(fqcn: String): String {
        val raw = fqcn.substringAfterLast('.').substringAfterLast('$')
        return sanitizeName(raw).replaceFirstChar(Char::lowercase)
    }

    private fun sanitizeName(raw: String): String =
        raw.replace(Regex("[^A-Za-z0-9_]"), "_")
            .replace(Regex("_+"), "_")
            .trim('_')
            .ifBlank { "value" }

    private fun ValidatedBinding.requiresDclHolder(): Boolean =
        declaredScope != null && kind != BindingKind.PROVIDED_ALIAS
}
